name: Build & Release DevPilot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test-build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
          pip install pyinstaller

      - name: Run tests
        run: |
          PYTHONPATH=src pytest

      - name: Build wheel and sdist
        run: python -m build

      - name: Build PyInstaller binary
        run: pyinstaller devpilot.spec

      - name: Upload Release Assets (GitHub Releases only)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/devpilot
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to PyPI (only on tagged releases)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          python -m pip install twine
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

