name: Build & Release DevPilot

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags

jobs:
  build-test-publish:
    name: Build, Test, and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write          
      id-token: write          

    environment:
      name: pypi               
      url: https://pypi.org/p/devpilot-hq 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build
          pip install .[dev]
          pip install pyinstaller

      - name: Run tests
        run: |
          PYTHONPATH=src pytest

      - name: Build wheel and sdist
        run: python -m build

      - name: Build PyInstaller binary
        run: pyinstaller devpilot.spec

      - name: Upload GitHub Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/devpilot
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move PyInstaller binary out of dist
        run: |
          mkdir -p release_assets/
          mv dist/devpilot release_assets/


      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip-existing: true

